const logo = require('../assets/logo.png')
const rightarrow = require('../assets/rightarrow.png')
const facebook = require('../assets/facebook.png')
const social = require('../assets/social.png')
const apple = require('../assets/apple.png')
const human = require('../assets/human.png')
const settings = require('../assets/settings.png')
const list = require('../assets/list.png')
const calendar = require('../assets/calendar.png')
const kanban = require('../assets/kanban.png')
const arrowdown = require('../assets/arrowdown.png')
const add = require('../assets/add.png')
const note = require('../assets/note.png')
const noproject = require('../assets/noproject.json')
const arrowRight = require('../assets/arrowRight.png')
const label = require('../assets/label.png')
const oval = require('../assets/oval.png')

const more = require('../assets/more.png')
const music = require('../assets/music.png')
const menu = require('../assets/menu.png')
const trash = require('../assets/trash.png')
const plus = require('../assets/plus.png')

export {oval,logo,rightarrow,plus,trash,music,menu,more,facebook,social,apple,human,settings,list,calendar,kanban,arrowdown,add,note,noproject,arrowRight,label};